# Schema for the configuration files of the ifthenelse config entity. 

if_then_else.rule.*:
  type: config_entity 
  label: 'If Then Else Rules'
  mapping: 
    id: 
      type: string 
      label: 'ID' 
    label: 
      type: label 
      label: 'Label' 
    active: 
      type: boolean 
      label: 'Active'
    module:
      type: string
      label: 'Module'
    event:
      type: string
      label: 'Event'
    condition:
      type: string
      label: 'Condition'
    data:
      type: text
      label: 'Data'
    processed_data:
      type: text
      label: 'Processed Data'
    weight:
      type: integer
      label: 'Weight'
